/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.WindowConstants;

/**
 *
 * @author crysuar
 */
public class Arreglos2 extends javax.swing.JFrame {

    /**
     * Creates new form Arreglos2
     */
    public Arreglos2() {
        initComponents();
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Llenar Arreglo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 286, Short.MAX_VALUE)
                .addComponent(jButton2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(0, 276, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //SOLICITO EL TAMAÑO DEL ARREGLO
        String x = JOptionPane.showInputDialog(null, "Introduce el Tamaño del arreglo: ", "Arreglo 2", JOptionPane.INFORMATION_MESSAGE);
        
        //CONVERION DE STRING A INT
        int tamaArray = Integer.parseInt(x);
        
        //INICIALIZAR ARREGLO
        String[] mascotas = new String[tamaArray];
        
        //LLENAR ARREGLO
        for(int i = 0; i < tamaArray; i++){
            mascotas[i] = JOptionPane.showInputDialog(null, "Escribe una Mascota Humano: ","Mascotas",JOptionPane.INFORMATION_MESSAGE);
        }
        JOptionPane.showMessageDialog(null, "Arreglo Lleno", "Alerta", JOptionPane.INFORMATION_MESSAGE);
        //CREAR UN JPANEL COMO CONTENEDOR DE CONTROLES
        JPanel jpanel = (JPanel)this.getContentPane();
        jpanel.setLayout(null);
        jpanel.setBackground(Color.PINK);
        //CREAR UN ARREGLO DE TIPO JLABEL
        JLabel[] etiquetas = new JLabel[tamaArray];
        //CREAR ETIQUETAS Y AGREGARLAS AL PANEL CON EL ARREGLO DE MASCOTAS
        for(int i = 0; i<tamaArray; i++){
            etiquetas[i]= new JLabel(mascotas[i]);
            etiquetas[i].setBounds(150,(i+1)*40,100,30);
            jpanel.add(etiquetas[i],null);
        }
        //CREAR UN ARREGLO DE TIPO JTEXTFIELD
        JTextField[] cajas = new JTextField[tamaArray];
        //CREAR ETIQUETAS Y AGREGARLAS AL PANEL CON EL ARREGLO DE MASCOTAS
        for(int i = 0; i<tamaArray; i++){
            cajas[i]= new JTextField(mascotas[i]);
            cajas[i].setBounds(300,(i+1)*40,100,30);
            jpanel.add(cajas[i],null);
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arreglos2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arreglos2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arreglos2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arreglos2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Arreglos2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
