/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.WindowConstants;

/**
 *
 * @author PC-13
 */
public class List_Domicilio extends javax.swing.JFrame {
private DefaultListModel diseño;

private String name,address,number,email;

    public List_Domicilio(String name, String address, String number, String email) {
        this.name = name;
        this.address = address;
        this.number = number;
        this.email = email;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Override
        public String toString(){
            return name;
        }

    public List_Domicilio() {
        initComponents();
        
        jList1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        diseño = new DefaultListModel();
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BuAdd = new javax.swing.JButton();
        BuClear = new javax.swing.JButton();
        BuDelete = new javax.swing.JButton();
        TextName = new javax.swing.JTextField();
        TextAddress = new javax.swing.JTextField();
        TextPhone = new javax.swing.JTextField();
        TextEmail = new javax.swing.JTextField();
        LaName = new javax.swing.JLabel();
        LaAddress = new javax.swing.JLabel();
        LaPhone = new javax.swing.JLabel();
        LaEmail = new javax.swing.JLabel();
        TextAdvertencia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        LaName1 = new javax.swing.JLabel();
        LaAdress2 = new javax.swing.JLabel();
        LaNumber2 = new javax.swing.JLabel();
        LaEmail2 = new javax.swing.JLabel();
        ViewName = new javax.swing.JTextField();
        ViewAddress = new javax.swing.JTextField();
        ViewNumber = new javax.swing.JTextField();
        ViewEmail = new javax.swing.JTextField();
        Title = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BuAdd.setText("Agregar");
        BuAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuAddActionPerformed(evt);
            }
        });

        BuClear.setText("Limpiar");
        BuClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuClearActionPerformed(evt);
            }
        });

        BuDelete.setText("Eliminar");
        BuDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuDeleteActionPerformed(evt);
            }
        });

        TextPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPhoneActionPerformed(evt);
            }
        });

        TextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEmailActionPerformed(evt);
            }
        });

        LaName.setFont(new java.awt.Font("Microsoft JhengHei Light", 2, 18)); // NOI18N
        LaName.setText("Nombre");

        LaAddress.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 18)); // NOI18N
        LaAddress.setText("Direccion");

        LaPhone.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 18)); // NOI18N
        LaPhone.setText("Telefono");

        LaEmail.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 18)); // NOI18N
        LaEmail.setText("Correo");

        TextAdvertencia.setFont(new java.awt.Font("Liberation Serif", 2, 24)); // NOI18N
        TextAdvertencia.setText("Advertencias");
        TextAdvertencia.setCaretColor(new java.awt.Color(255, 0, 51));
        TextAdvertencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextAdvertenciaActionPerformed(evt);
            }
        });

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        LaName1.setFont(new java.awt.Font("Kalimati", 2, 14)); // NOI18N
        LaName1.setText("Nombre");

        LaAdress2.setFont(new java.awt.Font("Kalimati", 2, 14)); // NOI18N
        LaAdress2.setText("Direccion");

        LaNumber2.setFont(new java.awt.Font("Kalimati", 2, 14)); // NOI18N
        LaNumber2.setText("Telefono");

        LaEmail2.setFont(new java.awt.Font("Kalimati", 2, 14)); // NOI18N
        LaEmail2.setText("Correo");

        ViewEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewEmailActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Dyuthi", 2, 48)); // NOI18N
        Title.setText("Formulario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LaAdress2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LaName1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LaNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LaEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ViewName, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                                    .addComponent(ViewNumber)
                                    .addComponent(ViewAddress)
                                    .addComponent(ViewEmail)))
                            .addComponent(TextAdvertencia, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(BuAdd))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(BuDelete)
                                .addGap(75, 75, 75)
                                .addComponent(BuClear)))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextName, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addComponent(LaName)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addComponent(LaAddress))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TextAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                            .addComponent(TextEmail)))))
                            .addComponent(TextPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(LaPhone)
                                .addGap(164, 164, 164)
                                .addComponent(LaEmail)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(LaAddress))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LaName)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BuAdd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BuDelete)
                            .addComponent(BuClear)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LaPhone)
                            .addComponent(LaEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ViewName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LaName1))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ViewAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LaAdress2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ViewNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LaNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ViewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LaEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(TextAdvertencia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuAddActionPerformed
        // Agrega el metodo AgregarNombre:
        AddObject();
    }//GEN-LAST:event_BuAddActionPerformed

    private void BuDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuDeleteActionPerformed
        // TODO add your handling code here:
        EliminarNombre(jList1.getSelectedIndex());
    }//GEN-LAST:event_BuDeleteActionPerformed

    private void BuClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuClearActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_BuClearActionPerformed

    private void TextPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPhoneActionPerformed

    private void TextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEmailActionPerformed

    private void TextAdvertenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextAdvertenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextAdvertenciaActionPerformed

    private void ViewEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewEmailActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        int index = jList1.getSelectedIndex();
        
        List_Domicilio addList = (List_Domicilio)diseño.getElementAt(index);
        ViewName.setText(addList.getName());
        ViewAddress.setText(addList.getAddress());
        ViewNumber.setText(addList.getNumber());
        ViewEmail.setText(addList.getEmail());
    }//GEN-LAST:event_jList1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(List_Domicilio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(List_Domicilio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(List_Domicilio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(List_Domicilio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new List_Domicilio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuAdd;
    private javax.swing.JButton BuClear;
    private javax.swing.JButton BuDelete;
    private javax.swing.JLabel LaAddress;
    private javax.swing.JLabel LaAdress2;
    private javax.swing.JLabel LaEmail;
    private javax.swing.JLabel LaEmail2;
    private javax.swing.JLabel LaName;
    private javax.swing.JLabel LaName1;
    private javax.swing.JLabel LaNumber2;
    private javax.swing.JLabel LaPhone;
    private javax.swing.JTextField TextAddress;
    private javax.swing.JTextField TextAdvertencia;
    private javax.swing.JTextField TextEmail;
    private javax.swing.JTextField TextName;
    private javax.swing.JTextField TextPhone;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField ViewAddress;
    private javax.swing.JTextField ViewEmail;
    private javax.swing.JTextField ViewName;
    private javax.swing.JTextField ViewNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
    //Puros Metodos para los botones
    private void AddObject() {
        name = TextName.getText();
        address = TextAddress.getText();
        number = TextPhone.getText();
        email = TextEmail.getText();
        
          TextName.setText("");
          TextAddress.setText("");
          TextPhone.setText("");
          TextEmail.setText("");
          
          List_Domicilio addList = new List_Domicilio(name,address,number,email);
          diseño.addElement(addList);
          jList1.setModel(diseño); //Llenado del elemento nombre
          
          TextAdvertencia.setText("Datos Agregados");
    }
    
    

    private void EliminarNombre(int index) {
        if(index >= 0){
            diseño.removeElementAt(index);
            TextAdvertencia.setText("Se elimino elemento " +index);
        } else {
            JOptionPane.showMessageDialog(null,"Debe Seleccionar un Elemento",
                    "Error",JOptionPane.ERROR_MESSAGE);
            TextAdvertencia.setText("No Selecciono ningun Elemento");
        }
    }

    private void Limpiar() {
        diseño.clear();
    }
    
    //Seleccion Item
    
    
    
}
